"""Fix Users (add deleted roles)

Revision ID: 45c266b9b6ca
Revises: 7658c5361bda
Create Date: 2025-03-06 21:47:19.737263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c266b9b6ca'
down_revision: Union[str, None] = '7658c5361bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
