"""Added review, rating and criteria models

Revision ID: 7658c5361bda
Revises: d22710eb853c
Create Date: 2025-03-06 21:42:27.668472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7658c5361bda'
down_revision: Union[str, None] = 'd22710eb853c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('energy_id', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['energy_id'], ['energetics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.drop_index('ix_energy_id', table_name='energy')
    op.drop_index('ix_energy_name', table_name='energy')
    op.drop_table('energy')
    op.drop_index('ix_brand_id', table_name='brand')
    op.drop_index('ix_brand_name', table_name='brand')
    op.drop_table('brand')
    op.add_column('ratings', sa.Column('review_id', sa.Integer(), nullable=False))
    op.add_column('ratings', sa.Column('rating_value', sa.Numeric(precision=3, scale=1), nullable=False))
    op.drop_constraint('ratings_user_id_fkey', 'ratings', type_='foreignkey')
    op.drop_constraint('ratings_energy_id_fkey', 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'reviews', ['review_id'], ['id'])
    op.drop_column('ratings', 'rating')
    op.drop_column('ratings', 'user_id')
    op.drop_column('ratings', 'energy_id')
    op.drop_column('ratings', 'review')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('review', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ratings', sa.Column('energy_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ratings', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ratings', sa.Column('rating', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key('ratings_energy_id_fkey', 'ratings', 'energetics', ['energy_id'], ['id'])
    op.create_foreign_key('ratings_user_id_fkey', 'ratings', 'users', ['user_id'], ['id'])
    op.drop_column('ratings', 'rating_value')
    op.drop_column('ratings', 'review_id')
    op.create_table('brand',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('brand_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='brand_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_brand_name', 'brand', ['name'], unique=True)
    op.create_index('ix_brand_id', 'brand', ['id'], unique=False)
    op.create_table('energy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name='energy_brand_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='energy_pkey')
    )
    op.create_index('ix_energy_name', 'energy', ['name'], unique=True)
    op.create_index('ix_energy_id', 'energy', ['id'], unique=False)
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
